micronaut:
  endpoints:
    beans:
      enabled: true
      sensitive: false

jpa.default.properties.hibernate.hbm2ddl.auto: update
datasources.default.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/payroll_db
datasources.default.username: ${PAYROLL_USER:payroll_admin}
datasources.default.password: ${PAYROLL_PASSWORD}
datasources.default.driver-class-name: com.mysql.cj.jdbc.Driver
jpa.default.properties.hibernate.show_sql: true
